### ISSUE TITLE
How do I start it

### ISSUE THREAD

**Issue by joni909** [vanyasem/Unity8-Arch#1]
how can I start Unity8?

**Comment by joni909** [comment]
i used miral-app unity8 in tty3 that started something but crashed

**Comment by timjp87** [comment]
Wondering that aswell. I tried "miral-desktop" and "miral-shell" and launch "unity8" after that, but it didn't work. I had to install qterminal for "miral-desktop" to even work, since it tries to launch that directly as terminal.

**Comment by vanyasem** [comment]
You cannot start it, it's WIP

**Comment by vanyasem** [comment]
If you know what you're doing, you can run the tests manually. But you cannot start Unity8 yet.

**Comment by joni909** [comment]
Ok thanks

**Comment by vanyasem** [comment]
Btw @timjp87 qt5-wayland is listed as an optional dep for mir. And it is in fact optional, it's only required for the demos.

**Comment by vanyasem** [comment]
It is installable now! Just follow [the simple instructions](https://github.com/vanyasem/Unity8-Arch#installation) in the repo.
