### ISSUE TITLE
[Question] Will this include the mobile interface of Ubuntu Touch?

### ISSUE THREAD

**Issue by ShapeShifter499** [vanyasem/Unity8-Arch#4]
I was looking into trying to install Ubuntu Touch on my "Nuvision Solo 10 Draw" which is a x86_64 tablet. I liked the looks of the touch focused interface I saw demoed in videos online. Their page currently mentions for "desktops" you can try Unity 8. But I'm wondering if I can get Unity 8 to work well for my touchscreen tablet. 

I would probably just jump to Ubuntu but I already run Arch Linux on a lot of my stuff and I'm very comfortable with how it all works.

**Comment by vanyasem** [comment]
There is no such thing as "the mobile interface". Unity8 itself is the DE, and "the mobile interface" is a toggle switch between different modes within the DE. You get to choose from "desktop", "tablet", and "phone"

Unity8 for x86_64 is not ready overall, it doesn't work properly even on Ubuntu 18.04, so I guess you might want to wait for it to get more stable.

**Comment by ShapeShifter499** [comment]
I'll wait for it to be more stable then, but I like the fact you can switch the style of the interface.

**Comment by vanyasem** [comment]
@ShapeShifter499 you can actually do that on mobile too ! you can connect an external monitor and it will switch to desktop mode - very handy with a BT mouse and keyboard :)
