### ISSUE TITLE
Repository server is down

### ISSUE THREAD

**Issue by Depau** [vanyasem/Unity8-Arch#6]
Hi,
I noticed the server behind [unity8.mynameisivan.ru](https://unity8.mynameisivan.ru) is currently down.

**Comment by Austcool-Walker** [comment]
yes ageed I wanted to try to use it @Depau

**Comment by vanyasem** [comment]
The server is up again - I threw up a couple weeks ago and physically shut down the server. We all have tough times in life - that was one of them. I apologize for that, that was as unproffesional as it gets.

**Comment by Depau** [comment]
Thanks for bringing it up again. We all have tough times, you don't have to apologise for that :)

Have a good day
